# Generated by Django 3.0 on 2024-08-13 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    atomic = False
    dependencies = [
        ('oc_lettings_site', '0001_initial'),
    ]

    database_operations = [
        migrations.AlterModelTable(
            name='Address',
            table='lettings_address'
        ),
        migrations.AlterField(
            model_name='letting',
            name='address',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to='oc_lettings_site.Address'),
        ),

        migrations.AlterModelTable(
            name='Letting',
            table='lettings_letting'
        ),
        migrations.AlterModelTable(
            name='Profile',
            table='profiles_profile'
        ),
    ]
    state_operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Letting',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=database_operations,
            state_operations=state_operations
        )
    ]
