# Generated by Django 3.0 on 2024-08-14 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oc_lettings_site', '0002_auto_20240814_0016'),
    ]

    state_operations = [
        migrations.DeleteModel(
            name='Address',
        ),
        migrations.DeleteModel(
            name='Letting',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=None,
            state_operations=state_operations
        )
    ]
