name: Build & Deploy OC_Lettings_Site
on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    name: Build & Deploy OC_Lettings_Site for Beginner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checlout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 17
      - name: Unit Tests
        run: |
          mvn -B test --file lettings/tests.py
          mvn -B test --file profiles/tests.py
      - name : Build the Application
        run: |
          mvn -B test --file lettings/tests.py
          mvn -B test --file profiles/tests.py
