name: Build Deploy OC_Lettings_Site
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  pytest:
    name: Run Pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Unit & Integration Tests
        run: |
          pip install -r requirements.txt
          pytest
  flake8:
    name: Run Flake8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: PEP8 Compatibility Tests
        run: |
          pip install -r requirements.txt
          flake8
  docker:
    name: Push Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Login Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_TOKEN}}
      - name: Push Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/oc-lettings-site:latest
  deploy:
    needs: docker
    name: Deploy Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Deploy Using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script_stop: true
          script: |
            echo "=========== Deploy Website ==========="
            docker stop $(docker ps -a -q)
            docker rm $(docker ps -a -q)
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/oc-lettings-site:latest
            docker run -it -d -p 8000:8000 ${{ secrets.DOCKER_HUB_USERNAME }}/oc-lettings-site:latest /app/entrypoint.sh
            echo "=========== Deploy Website ==========="