name: Build & Deploy OC_Lettings_Site
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  pytest:
    name: Run Pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Unit & Integration Tests
        run: |
          pip install -r requirements.txt
          pytest
  flake8:
    name: Run Flake8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: PEP8 Compatibility Tests
        run: |
          pip install -r requirements.txt
          flake8
