name: Build Deploy OC_Lettings_Site
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  pytest:
    name: Run Pytest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Unit & Integration Tests
        run: |
          pip install -r requirements.txt
          pytest
  flake8:
    name: Run Flake8
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: PEP8 Compatibility Tests
        run: |
          pip install -r requirements.txt
          flake8
  docker:
    name: Push Docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Login Docker
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_HUB_USERNAME}}
          password: ${{secrets.DOCKER_HUB_TOKEN}}
      - name: Push Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .
          push: false
          # tags: ${{ secrets.DOCKER_HUB_USERNAME }}/oc-lettings-site:latest
          tags: o0nekov0o/oc-lettings-site:latest